# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Totem_Max"
product_name = "Totem_Max"
vendor_id = 0xFEED
product_id = 0xCAD1
manufacturer = "Cube_Studio"
board = "nice!nano_v2"


[layout]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true
rows = 10
cols = 6
layers = 6

matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5)                        (5,5) (5,4) (5,3) (5,2) (5,1) (5,0)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5)                        (6,5) (6,4) (6,3) (6,2) (6,1) (6,0)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5)                        (7,5) (7,4) (7,3) (7,2) (7,1) (7,0)
(3,0) (3,1) (3,2) (3,3) (3,4) (3,5)                        (8,5) (8,4) (8,3) (8,2) (8,1) (8,0)
            (4,2) (4,3) (4,4) (4,5)                        (9,5) (9,4) (9,3) (9,2)
"""


[[layer]]
name = "base_layer"
keys = """
Escape Kc1 Kc2 Kc3 Kc4 Kc5                      Kc6, Kc7, Kc8, Kc9,   Kc0,     Backspace
Tab    Q   W   E   R   T                        Y    U    I    O      P        Backslash
caps   A   S   D   D   F                        H    J    K    K   Semicolon   Quote
LShift Z   X   C   V   B                        N    M  Comma  Dot   Slash     RShift
       LCtrl LGui LAlt  Space            Space RAlt RGui RCtrl
"""
[[layer]]
name = "layer2"
keys = """
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
                   TRNS TRNS TRNS TRNS     TRNS TRNS TRNS TRNS
"""


[[layer]]
name = "layer3"
keys = """
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
                   TRNS TRNS TRNS TRNS     TRNS TRNS TRNS TRNS
"""

[[layer]]
name = "layer4"
keys = """
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
                   TRNS TRNS TRNS TRNS     TRNS TRNS TRNS TRNS
"""
[[layer]]
name = "layer5"
keys = """
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
                   TRNS TRNS TRNS TRNS     TRNS TRNS TRNS TRNS
"""
[[layer]]
name = "layer6"
keys = """
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
TRNS  TRNS TRNS TRNS TRNS TRNS                 TRNS  TRNS TRNS TRNS TRNS TRNS
                   TRNS TRNS TRNS TRNS     TRNS TRNS TRNS TRNS
"""

[split]
# split connection type
connection = "ble"

[split.central]
rows = 5
cols = 6
row_offset = 0
col_offset = 0

[split.central.matrix]
matrix_type = "normal"
row_pins = ["P0_09", "P0_10", "P1_11", "P1_13","P1_15"]
col_pins= ["P1_06", "P1_04", "P0_11", "P1_00", "P0_24", "P0_22"]

[[split.peripheral]]
rows = 5
cols = 6
row_offset = 5
col_offset = 0

[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["P0_09", "P0_10", "P1_11", "P1_13","P1_15"]
col_pins= ["P0_22", "P0_24", "P1_00", "P0_11", "P1_04", "P1_06"]
