# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Totem_Max"
product_name = "Totem_Max"
vendor_id = 0xFEED
product_id = 0xCAD1
manufacturer = "Cube_Studio"
chip = "nrf52840"


[layout]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true
rows = 10
cols = 6
layers = 5

keymap = [
    [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5"],
        ["Tab", "Q", "W", "E", "R", "T"],
        ["Escape", "A", "S", "D", "F", "G"],
        ["LShift", "Z", "X", "C", "V", "B"],
        ["__", "__", "__", "__", "__", "__"],
        ["Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Minus"],
        ["Y", "U", "I", "O", "P", "Backslash"],
        ["H", "J", "K", "L", "Semicolon", "Quote"],
        ["N", "M", "Comma", "Dot", "Slash", "RShift"],
         ["__", "__", "__", "__", "__", "__"]
    ],
   [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5"],
        ["Tab", "Q", "W", "E", "R", "T"],
        ["Escape", "A", "S", "D", "F", "G"],
        ["LShift", "Z", "X", "C", "V", "B"],
        ["__", "__", "__", "__", "__", "__"],
        ["Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Minus"],
        ["Y", "U", "I", "O", "P", "Backslash"],
        ["H", "J", "K", "L", "Semicolon", "Quote"],
        ["N", "M", "Comma", "Dot", "Slash", "RShift"],
         ["__", "__", "__", "__", "__", "__"]
    ],
   [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5"],
        ["Tab", "Q", "W", "E", "R", "T"],
        ["Escape", "A", "S", "D", "F", "G"],
        ["LShift", "Z", "X", "C", "V", "B"],
        ["__", "__", "__", "__", "__", "__"],
        ["Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Minus"],
        ["Y", "U", "I", "O", "P", "Backslash"],
        ["H", "J", "K", "L", "Semicolon", "Quote"],
        ["N", "M", "Comma", "Dot", "Slash", "RShift"],
         ["__", "__", "__", "__", "__", "__"]
    ],
   [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5"],
        ["Tab", "Q", "W", "E", "R", "T"],
        ["Escape", "A", "S", "D", "F", "G"],
        ["LShift", "Z", "X", "C", "V", "B"],
        ["__", "__", "__", "__", "__", "__"],
        ["Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Minus"],
        ["Y", "U", "I", "O", "P", "Backslash"],
        ["H", "J", "K", "L", "Semicolon", "Quote"],
        ["N", "M", "Comma", "Dot", "Slash", "RShift"],
         ["__", "__", "__", "__", "__", "__"]
    ],
    [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5"],
        ["Tab", "Q", "W", "E", "R", "T"],
        ["Escape", "A", "S", "D", "F", "G"],
        ["LShift", "Z", "X", "C", "V", "B"],
        ["__", "__", "__", "__", "__", "__"],
        ["Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Minus"],
        ["Y", "U", "I", "O", "P", "Backslash"],
        ["H", "J", "K", "L", "Semicolon", "Quote"],
        ["N", "M", "Comma", "Dot", "Slash", "RShift"],
         ["__", "__", "__", "__", "__", "__"]
    ]
]



[split]
# split connection type
connection = "ble"

[split.central]
rows = 5
cols = 6
row_offset = 0
col_offset = 0

[split.central.matrix]
matrix_type = "normal"
row_pins = ["P0_09", "P0_10", "P1_11", "P1_13","P1_15"]
col_pins= ["P0_22", "P0_24", "P1_00", "P0_11", "P1_04", "P1_06"]

[[split.peripheral]]
rows = 5
cols = 6
row_offset = 5
col_offset = 0

[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["P0_09", "P0_10", "P1_11", "P1_13","P1_15"]
col_pins= ["P0_22", "P0_24", "P1_00", "P0_11", "P1_04", "P1_06"]
